/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is true */

#line 5 "ex.c"
void __globinit_ex(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 104 "/usr/include/x86_64-linux-gnu/mpich/mpi.h"
typedef int MPI_Datatype;
#line 287 "/usr/include/x86_64-linux-gnu/mpich/mpi.h"
typedef int MPI_Comm;
#line 451 "/usr/include/x86_64-linux-gnu/mpich/mpi.h"
typedef int MPI_Request;
#line 585 "/usr/include/x86_64-linux-gnu/mpich/mpi.h"
struct MPI_Status {
   int count_lo ;
   int count_hi_and_cancelled ;
   int MPI_SOURCE ;
   int MPI_TAG ;
   int MPI_ERROR ;
};
#line 585 "/usr/include/x86_64-linux-gnu/mpich/mpi.h"
typedef struct MPI_Status MPI_Status;
#line 939
extern int MPI_Isend(void const   *buf , int count , MPI_Datatype datatype , int dest ,
                     int tag , MPI_Comm comm , MPI_Request *request ) ;
#line 947
extern int MPI_Irecv(void *buf , int count , MPI_Datatype datatype , int source ,
                     int tag , MPI_Comm comm , MPI_Request *request ) ;
#line 949
extern int MPI_Wait(MPI_Request *request , MPI_Status *status ) ;
#line 1076
extern int MPI_Comm_size(MPI_Comm comm , int *size ) ;
#line 1077
extern int MPI_Comm_rank(MPI_Comm comm , int *rank ) ;
#line 1125
extern int MPI_Init(int *argc , char ***argv ) ;
#line 1126
extern int MPI_Finalize(void) ;
#line 332 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 5 "ex.c"
void main(int argc , char **argv ) 
{ int rank ;
  int size ;
  int buf ;
  int input ;
  MPI_Request req2 ;
  MPI_Request req1 ;
  MPI_Status st1 ;
  MPI_Status st2 ;
  MPI_Request req2___0 ;
  MPI_Request req1___0 ;
  MPI_Status st1___0 ;
  MPI_Status st2___0 ;

  {
  __globinit_ex();
  __CrestCall(2, 1);
  __CrestStore(1, (unsigned long )(& argc));
#line 6
  MPI_Init(& argc, & argv);
  __CrestClearStack(3);
  __CrestLoad(4, (unsigned long )0, (long long )1140850688);
#line 8
  MPI_Comm_rank(1140850688, & rank);
  __CrestClearStack(5);
  __CrestLoad(6, (unsigned long )0, (long long )1140850688);
#line 9
  MPI_Comm_size(1140850688, & size);
  __CrestClearStack(7);
  __CrestLoad(8, (unsigned long )0, (long long )1);
  __CrestStore(9, (unsigned long )(& input));
#line 11
  input = 1;
#line 14
  printf((char const   * __restrict  )"Before if\n");
  __CrestClearStack(10);
  {
  __CrestLoad(13, (unsigned long )(& input), (long long )input);
  __CrestLoad(12, (unsigned long )0, (long long )2);
  __CrestApply2(11, 13, (long long )(input != 2));
#line 15
  if (input != 2) {
    __CrestBranch(14, 3, 1);
#line 16
    printf((char const   * __restrict  )"After if input\n");
    __CrestClearStack(16);
    {
    __CrestLoad(19, (unsigned long )(& rank), (long long )rank);
    __CrestLoad(18, (unsigned long )0, (long long )0);
    __CrestApply2(17, 12, (long long )(rank == 0));
#line 17
    if (rank == 0) {
      __CrestBranch(20, 5, 1);
#line 18
      printf((char const   * __restrict  )"After if rank 0\n");
      __CrestClearStack(22);
      __CrestLoad(23, (unsigned long )0, (long long )1);
      __CrestLoad(24, (unsigned long )0, (long long )1275069445);
      __CrestLoad(25, (unsigned long )0, (long long )1);
      __CrestLoad(26, (unsigned long )0, (long long )99);
      __CrestLoad(27, (unsigned long )0, (long long )1140850688);
#line 21
      MPI_Isend((void const   *)(& rank), 1, 1275069445, 1, 99, 1140850688, & req1);
      __CrestClearStack(28);
      __CrestLoad(29, (unsigned long )0, (long long )1);
      __CrestLoad(30, (unsigned long )0, (long long )1275069445);
      __CrestLoad(31, (unsigned long )0, (long long )1);
      __CrestLoad(32, (unsigned long )0, (long long )98);
      __CrestLoad(33, (unsigned long )0, (long long )1140850688);
#line 22
      MPI_Irecv((void *)(& buf), 1, 1275069445, 1, 98, 1140850688, & req2);
      __CrestClearStack(34);
#line 23
      MPI_Wait(& req1, & st1);
      __CrestClearStack(35);
#line 24
      MPI_Wait(& req2, & st2);
      __CrestClearStack(36);
      __CrestLoad(37, (unsigned long )(& rank), (long long )rank);
      __CrestLoad(38, (unsigned long )(& buf), (long long )buf);
#line 25
      printf((char const   * __restrict  )"recvd rank %d from %d\n", rank, buf);
      __CrestClearStack(39);
    } else {
      __CrestBranch(21, 6, 0);
#line 28
      printf((char const   * __restrict  )"After if rank 1\n");
      __CrestClearStack(40);
      __CrestLoad(41, (unsigned long )0, (long long )1);
      __CrestLoad(42, (unsigned long )0, (long long )1275069445);
      __CrestLoad(43, (unsigned long )0, (long long )0);
      __CrestLoad(44, (unsigned long )0, (long long )98);
      __CrestLoad(45, (unsigned long )0, (long long )1140850688);
#line 31
      MPI_Isend((void const   *)(& rank), 1, 1275069445, 0, 98, 1140850688, & req1___0);
      __CrestClearStack(46);
      __CrestLoad(47, (unsigned long )0, (long long )1);
      __CrestLoad(48, (unsigned long )0, (long long )1275069445);
      __CrestLoad(49, (unsigned long )0, (long long )0);
      __CrestLoad(50, (unsigned long )0, (long long )99);
      __CrestLoad(51, (unsigned long )0, (long long )1140850688);
#line 32
      MPI_Irecv((void *)(& buf), 1, 1275069445, 0, 99, 1140850688, & req2___0);
      __CrestClearStack(52);
#line 33
      MPI_Wait(& req1___0, & st1___0);
      __CrestClearStack(53);
#line 34
      MPI_Wait(& req2___0, & st2___0);
      __CrestClearStack(54);
      __CrestLoad(55, (unsigned long )(& rank), (long long )rank);
      __CrestLoad(56, (unsigned long )(& buf), (long long )buf);
#line 35
      printf((char const   * __restrict  )"recvd rank %d from %d\n", rank, buf);
      __CrestClearStack(57);
    }
    }
  } else {
    __CrestBranch(15, 7, 0);
#line 39
    printf((char const   * __restrict  )"Else branch\n");
    __CrestClearStack(58);
  }
  }
#line 42
  MPI_Finalize();
  __CrestClearStack(59);
  {
  __CrestReturn(60);
#line 5
  return;
  }
}
}
void __globinit_ex(void) 
{ 

  {
  __CrestInit();
}
}
